default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: rails_react_crud_app_development

test:
  <<: *default
  database: rails_react_crud_app_test

production:
  <<: *default
  database: rails_react_crud_app_production
  username: rails_react_crud_app
  password: <%= ENV['RAILS_REACT_CRUD_APP_DATABASE_PASSWORD'] %>
